version: '3'
services:
  aspnetcoreprod:
    build:
      context: .
      dockerfile: prod.Dockerfile
    ports:
    - "8081:80"
    networks:
    - aspnetcore-network-prod
    depends_on:
    - mssqlprod
    environment:
    - "ConnectionStrings:DefaultConnection=Server=mssqlprod;Database=EFGetStarted.AspNetCore.NewDb;uid=sa;pwd=P@ssword66prod;ConnectRetryCount=0"
  mssqlprod:
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - "1433:1433"
    environment:
    - "ACCEPT_EULA=Y"
    - "SA_PASSWORD=P@ssword66prod"
    networks:
    - aspnetcore-network-prod
networks:
  aspnetcore-network-prod:
    driver: bridge